---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    capability.openshift.io/name: MachineAPI
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2024-12-03T19:19:17Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
        f:relatedObjects: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:versions: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2026-06-09T05:28:19Z"
  name: control-plane-machine-set
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "7967127801"
  uid: 5cd4cd30-4f18-480b-a3f5-e97b18efa03c
spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-12-03T19:27:25Z"
    message: cluster operator is upgradable
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-12-03T19:27:25Z"
    reason: AllReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-13T16:39:48Z"
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2024-12-13T16:54:42Z"
    reason: AllReplicasUpdated
    status: "False"
    type: Progressing
  extension: null
  relatedObjects:
  - group: ""
    name: openshift-machine-api
    resource: namespaces
  - group: machine.openshift.io
    name: ""
    resource: controlplanemachinesets
  - group: machine.openshift.io
    name: ""
    resource: machines
  versions:
  - name: operator
    version: 4.21.18
