---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:19:17Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Degraded"}:
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Progressing"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: dns-operator
    operation: Update
    subresource: status
    time: "2026-06-12T21:11:04Z"
  name: dns
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "7987806216"
  uid: b54fc293-d633-4004-a79a-c0b05f9792d7
spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-12-03T19:24:53Z"
    message: DNS "default" is available.
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-12T21:11:04Z"
    message: Desired and current number of DNSes are equal
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2026-06-09T05:06:33Z"
    reason: DNSNotDegraded
    status: "False"
    type: Degraded
  - lastTransitionTime: "2024-12-03T19:24:28Z"
    message: 'DNS default is upgradeable: DNS Operator can be upgraded'
    reason: DNSUpgradeable
    status: "True"
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: ""
    name: openshift-dns-operator
    resource: namespaces
  - group: operator.openshift.io
    name: default
    resource: dnses
  - group: ""
    name: openshift-dns
    resource: namespaces
  versions:
  - name: operator
    version: 4.21.18
  - name: coredns
    version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9d189a292563f4173eb3cb534693a4fdc714d0c04255dca0aa7062663e6985ec
  - name: openshift-cli
    version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9962b794b6ee6a291133012dccc65bd682122eb91abf4f5c36217194c8949a14
  - name: kube-rbac-proxy
    version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0299bce77fb9f786465c23efc36aca6557ddea63b9642c2176b17f827addddb2
