---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    capability.openshift.io/name: ImageRegistry
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:19:17Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            f:message: {}
            f:reason: {}
          k:{"type":"Degraded"}:
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Progressing"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: cluster-image-registry-operator
    operation: Update
    subresource: status
    time: "2026-06-12T21:11:04Z"
  name: image-registry
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "7987806227"
  uid: b8f355cc-8f0b-4740-856f-9d93cf1ff059
spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-12-03T19:33:43Z"
    message: |-
      Available: The registry is ready
      NodeCADaemonAvailable: The daemon set node-ca has available replicas
      ImagePrunerAvailable: Pruner CronJob has been created
    reason: Ready
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-12T21:11:04Z"
    message: |-
      Progressing: The registry is ready
      NodeCADaemonProgressing: The daemon set node-ca is deployed
    reason: Ready
    status: "False"
    type: Progressing
  - lastTransitionTime: "2026-04-14T05:22:08Z"
    reason: AsExpected
    status: "False"
    type: Degraded
  extension: null
  relatedObjects:
  - group: imageregistry.operator.openshift.io
    name: cluster
    resource: configs
  - group: imageregistry.operator.openshift.io
    name: cluster
    resource: imagepruners
  - group: rbac.authorization.k8s.io
    name: system:registry
    resource: clusterroles
  - group: rbac.authorization.k8s.io
    name: registry-registry-role
    resource: clusterrolebindings
  - group: rbac.authorization.k8s.io
    name: openshift-image-registry-pruner
    resource: clusterrolebindings
  - group: ""
    name: openshift-image-registry
    resource: namespaces
  versions:
  - name: operator
    version: 4.21.18
