---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    capability.openshift.io/name: Ingress
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:19:17Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2024-12-03T19:19:18Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Progressing"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Upgradeable"}:
            f:reason: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: ingress-operator
    operation: Update
    subresource: status
    time: "2026-06-09T07:20:07Z"
  name: ingress
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "7967671511"
  uid: 2518815f-c740-4359-9cac-f18a2f83e50e
spec: {}
status:
  conditions:
  - lastTransitionTime: "2025-12-09T12:59:59Z"
    message: The "default" ingress controller reports Available=True.
    reason: IngressAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-09T07:20:07Z"
    message: desired and current number of IngressControllers are equal
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-12-03T19:34:27Z"
    message: The "default" ingress controller reports Degraded=False.
    reason: IngressNotDegraded
    status: "False"
    type: Degraded
  - lastTransitionTime: "2024-12-03T19:24:28Z"
    reason: IngressControllersUpgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-12-03T19:24:28Z"
    reason: AsExpected
    status: "False"
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: ""
    name: openshift-ingress-operator
    resource: namespaces
  - group: operator.openshift.io
    name: ""
    namespace: openshift-ingress-operator
    resource: ingresscontrollers
  - group: ingress.operator.openshift.io
    name: ""
    namespace: openshift-ingress-operator
    resource: dnsrecords
  - group: ""
    name: openshift-ingress
    resource: namespaces
  - group: ingress.operator.openshift.io
    name: ""
    namespace: openshift-ingress
    resource: dnsrecords
  - group: ""
    name: openshift-ingress-canary
    resource: namespaces
  - group: gateway.networking.k8s.io
    name: ""
    resource: gatewayclasses
  - group: gateway.networking.k8s.io
    name: ""
    resource: gateways
  versions:
  - name: operator
    version: 4.21.18
  - name: ingress-controller
    version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bf7d8b424579d1756c1be5b17c28d91cc55406d545e92ee7970df6e3fd0e61f5
  - name: canary-server
    version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a34a8675d80bec4c5781aa74dfb91df11a7a09b98ce4778511e161004163b3e0
