---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    capability.openshift.io/name: Insights
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:19:17Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"ClusterTransferAvailable"}:
            f:message: {}
            f:reason: {}
          k:{"type":"GatheringDisabled"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"RemoteConfigurationAvailable"}:
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
          k:{"type":"RemoteConfigurationValid"}:
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
          k:{"type":"SCAAvailable"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
        f:extension:
          f:lastReportTime: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: insights-operator
    operation: Update
    subresource: status
    time: "2026-06-12T20:41:47Z"
  name: insights
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "7987689058"
  uid: df871842-f681-4de1-a7e8-785aa61a1f0d
spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-12-03T19:31:22Z"
    message: Insights works as expected
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-03T19:35:22Z"
    message: no available cluster transfer
    reason: NoClusterTransfer
    status: "False"
    type: ClusterTransferAvailable
  - lastTransitionTime: "2024-12-03T19:31:22Z"
    message: Insights works as expected
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2024-12-03T19:31:22Z"
    reason: AsExpected
    status: "False"
    type: Disabled
  - lastTransitionTime: "2025-11-13T07:29:22Z"
    message: Gathering is enabled
    reason: AsExpected
    status: "False"
    type: GatheringDisabled
  - lastTransitionTime: "2026-03-13T10:54:14Z"
    message: Monitoring the cluster
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2026-05-04T16:46:10Z"
    reason: Succeeded
    status: "True"
    type: RemoteConfigurationAvailable
  - lastTransitionTime: "2026-05-04T16:46:10Z"
    reason: Succeeded
    status: "True"
    type: RemoteConfigurationValid
  - lastTransitionTime: "2026-05-22T03:47:39Z"
    message: SCA certs successfully updated
    reason: Updated
    status: "True"
    type: SCAAvailable
  - lastTransitionTime: "2024-12-03T19:31:22Z"
    message: Insights operator can be upgraded
    reason: InsightsUpgradeable
    status: "True"
    type: Upgradeable
  extension:
    lastReportTime: "2026-06-12T20:41:47Z"
  relatedObjects:
  - group: ""
    name: openshift-insights
    resource: namespaces
  - group: apps
    name: insights-operator
    namespace: openshift-insights
    resource: deployments
  - group: ""
    name: pull-secret
    namespace: openshift-config
    resource: secrets
  - group: ""
    name: support
    namespace: openshift-config
    resource: secrets
  - group: ""
    name: gather
    namespace: openshift-insights
    resource: serviceaccounts
  - group: ""
    name: operator
    namespace: openshift-insights
    resource: serviceaccounts
  - group: ""
    name: metrics
    namespace: openshift-insights
    resource: services
  - group: ""
    name: service-ca-bundle
    namespace: openshift-insights
    resource: configmaps
  - group: operator.openshift.io
    name: cluster
    resource: insightsoperators
  versions:
  - name: operator
    version: 4.21.18
