---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:19:17Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2024-12-03T19:19:17Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            f:message: {}
          k:{"type":"Degraded"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Progressing"}:
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: cluster-kube-scheduler-operator
    operation: Update
    subresource: status
    time: "2026-06-09T06:20:01Z"
  name: kube-scheduler
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "7967390923"
  uid: 54b0fde3-5d9b-41bf-8e4c-574fe2e44769
spec: {}
status:
  conditions:
  - lastTransitionTime: "2026-06-09T06:20:01Z"
    message: 'NodeControllerDegraded: All master nodes are ready'
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2026-06-09T05:25:31Z"
    message: 'NodeInstallerProgressing: 3 nodes are at revision 50'
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-12-03T19:27:05Z"
    message: 'StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 50'
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-03T19:23:52Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-12-03T19:23:51Z"
    reason: NoData
    status: Unknown
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: kubeschedulers
  - group: config.openshift.io
    name: ""
    resource: schedulers
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-kube-scheduler
    resource: namespaces
  - group: ""
    name: openshift-kube-scheduler-operator
    resource: namespaces
  - group: controlplane.operator.openshift.io
    name: ""
    namespace: openshift-kube-apiserver
    resource: podnetworkconnectivitychecks
  - group: rbac.authorization.k8s.io
    name: system:openshift:operator:cluster-kube-scheduler-operator
    resource: clusterrolebindings
  versions:
  - name: raw-internal
    version: 4.21.18
  - name: kube-scheduler
    version: 1.34.8
  - name: operator
    version: 4.21.18
