---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  creationTimestamp: "2024-12-10T17:38:43Z"
  generation: 1
  labels:
    app: kubevirt-hyperconverged
    app.kubernetes.io/component: kubevirt-console-plugin
    app.kubernetes.io/managed-by: hco-operator
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.21.8
  managedFields:
  - apiVersion: console.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/part-of: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        .: {}
        f:backend:
          .: {}
          f:service:
            .: {}
            f:basePath: {}
            f:name: {}
            f:namespace: {}
            f:port: {}
          f:type: {}
        f:displayName: {}
        f:i18n:
          .: {}
          f:loadType: {}
        f:proxy: {}
    manager: hyperconverged-cluster-operator
    operation: Update
    time: "2026-05-26T13:17:55Z"
  name: kubevirt-plugin
  resourceVersion: "7883479904"
  uid: 69176614-87ba-4823-8c07-2d0c476ee344
spec:
  backend:
    service:
      basePath: /
      name: kubevirt-console-plugin-service
      namespace: openshift-cnv
      port: 9443
    type: Service
  displayName: Kubevirt Console Plugin
  i18n:
    loadType: ""
  proxy:
  - alias: kubevirt-apiserver-proxy
    authorization: UserToken
    endpoint:
      service:
        name: kubevirt-apiserver-proxy-service
        namespace: openshift-cnv
        port: 8080
      type: Service
