---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  creationTimestamp: "2024-12-03T19:32:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: networking-console-plugin
    app.kubernetes.io/managed-by: cluster-network-operator
    app.kubernetes.io/name: networking-console-plugin
    app.kubernetes.io/part-of: cluster-network-operator
  managedFields:
  - apiVersion: console.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
        f:ownerReferences:
          k:{"uid":"613484e4-cf55-4df0-af59-2ae11607f117"}: {}
      f:spec:
        f:backend:
          f:service:
            f:basePath: {}
            f:name: {}
            f:namespace: {}
            f:port: {}
          f:type: {}
        f:displayName: {}
        f:i18n:
          f:loadType: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2024-12-03T19:32:30Z"
  name: networking-console-plugin
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 613484e4-cf55-4df0-af59-2ae11607f117
  resourceVersion: "20680"
  uid: d0daab69-4b55-4e50-a6d2-41c24a778088
spec:
  backend:
    service:
      basePath: /
      name: networking-console-plugin
      namespace: openshift-network-console
      port: 9443
    type: Service
  displayName: Networking Console Plugin
  i18n:
    loadType: Preload
