---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: e0754fd591402a905fc2b1483401b5980464f1bde226cb034693b30bb7efc38d
  creationTimestamp: "2026-05-30T21:39:38Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: tekton-config
  managedFields:
  - apiVersion: console.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:operator.tekton.dev/last-applied-hash: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/part-of: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"10235742-40fd-4c7a-b356-f77965c5a115"}: {}
      f:spec:
        .: {}
        f:backend:
          .: {}
          f:service:
            .: {}
            f:basePath: {}
            f:name: {}
            f:namespace: {}
            f:port: {}
          f:type: {}
        f:displayName: {}
        f:i18n:
          .: {}
          f:loadType: {}
        f:proxy: {}
    manager: manifestival
    operation: Update
    time: "2026-05-30T21:39:38Z"
  name: pipelines-console-plugin
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonInstallerSet
    name: tekton-config-console-plugin-manifests-5zhtz
    uid: 10235742-40fd-4c7a-b356-f77965c5a115
  resourceVersion: "7910589029"
  uid: 8a32114e-4ace-41b5-b484-f8922a5990a2
spec:
  backend:
    service:
      basePath: /
      name: pipelines-console-plugin
      namespace: openshift-pipelines
      port: 8443
    type: Service
  displayName: Pipelines Console Plugin
  i18n:
    loadType: Preload
  proxy:
  - alias: tekton-results-api-service
    authorization: UserToken
    endpoint:
      service:
        name: tekton-results-api-service
        namespace: openshift-pipelines
        port: 8080
      type: Service
  - alias: multicluster-proxy
    authorization: UserToken
    endpoint:
      service:
        name: proxy-aae
        namespace: openshift-pipelines
        port: 443
      type: Service
