---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    olm.operatorframework.io/feature-set: experimental
  creationTimestamp: "2025-03-18T10:47:24Z"
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:olm.operatorframework.io/feature-set: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
      f:rules: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-03-13T11:04:05Z"
  name: catalogd-manager-role
  resourceVersion: "7414735654"
  uid: 25d78342-9272-402c-9540-35e948ebcfe3
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - clustercatalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - clustercatalogs/finalizers
  verbs:
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - clustercatalogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
