---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    olm.operatorframework.io/feature-set: experimental
  creationTimestamp: "2025-03-18T10:47:25Z"
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:olm.operatorframework.io/feature-set: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
      f:rules: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-03-13T11:04:05Z"
  name: catalogd-proxy-role
  resourceVersion: "7414735658"
  uid: 97b86163-253d-4e87-a2b4-d222158337de
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
