---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:29:33Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:29:33Z"
  name: console-extensions-reader
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "17125"
  uid: f385698d-167f-42ab-8230-0b3f9e0c73bd
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consoleclidownloads
  - consoleexternalloglinks
  - consolelinks
  - consolenotifications
  - consoleplugins
  - consolequickstarts
  - consolesamples
  - consoleyamlsamples
  verbs:
  - get
  - list
  - watch
