---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:29:35Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:labels:
          .: {}
          f:rbac.authorization.k8s.io/aggregate-to-admin: {}
          f:rbac.authorization.k8s.io/aggregate-to-edit: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:29:35Z"
  name: project-helm-chartrepository-editor
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "17149"
  uid: 32753efe-09da-49e0-a174-c0a66c47ec7d
rules:
- apiGroups:
  - helm.openshift.io
  resources:
  - projecthelmchartrepositories
  verbs:
  - get
  - list
  - update
  - create
  - watch
  - patch
  - delete
