---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    capability.openshift.io/name: CSISnapshot
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-03T19:19:42Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
    storage.openshift.io/aggregate-to-storage-admin: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
          f:kubernetes.io/cluster-service: {}
          f:storage.openshift.io/aggregate-to-storage-admin: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"57211e58-241c-464e-8d45-e1c29c5df9c6"}: {}
      f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-12-03T19:19:42Z"
  name: system:openshift:aggregate-snapshots-to-storage-admin
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 57211e58-241c-464e-8d45-e1c29c5df9c6
  resourceVersion: "1847"
  uid: 85a782e9-d62a-4952-8e3b-dc094cf0c681
rules:
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  - volumesnapshotcontents
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
